/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class AlarmScheduleCollectionView, AlarmScheduleHeaderView;

@interface AlarmScheduleView : _ADClientAddValueForScalarKey
{
    AlarmScheduleHeaderView *_headerView;
    AlarmScheduleCollectionView *_alarmsView;
    int _currentDay;
}

- (void)setCurrentDay:(int)fp8;
- (int)currentDay;
- (id)alarmsView;
- (id)headerView;
- (void)handleLocaleChange;
- (void)handleSignificantTimeChange;
- (void)layoutSubviews;
- (void)refreshHeader;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

