/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class NSDateFormatter, NSMutableArray;

@interface AlarmScheduleHeaderView : _ADClientAddValueForScalarKey
{
    NSMutableArray *_dateLabels;
    NSDateFormatter *_formatter;
    int _firstDayOfWeek;
    int _currentDayOfWeek;
    float _leftMargin;
    float _columnWidth;
}

+ (float)defaultHeight;
- (float)columnWidth;
- (float)leftMargin;
- (int)currentDayOfWeek;
- (void)setFirstDayOfWeek:(int)fp8;
- (int)firstDayOfWeek;
- (void)setCurrentDayOfWeek:(int)fp8;
- (void)handleLocaleChange;
- (void)setColumnWidth:(float)fp8;
- (void)setLeftMargin:(float)fp8;
- (void)updateDayLabelValues;
- (id)newDateLabel;
- (void)setBackgroundColor:(id)fp8;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

