/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class AlarmView;

@interface AlarmTableViewCell : UITableViewCell
{
    id <AlarmActiveDelegate> _alarmActiveDelegate;
    AlarmView *_alarmView;
    BOOL _enabled;
}

+ (float)defaultHeight;
- (void)layoutSubviews;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)willTransitionToState:(unsigned int)fp8;
- (void)_alarmActiveChanged:(id)fp8;
- (void)setAlarmActiveDelegate:(id)fp8;
- (void)refreshUI:(id)fp8 animated:(BOOL)fp12;
- (void)setBackgroundColor:(id)fp8;
- (void)internalSetBackgroundColor:(id)fp8;
- (void)dealloc;
- (id)init;

@end

