/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class AlarmView;

@interface AlarmSingleViewCollectionCell : _ADClientAddValueForScalarKey
{
    BOOL _enabled;
    id <AlarmActiveDelegate> _alarmActiveDelegate;
    AlarmView *_alarmView;
    unsigned int _index;
}

- (void)setIndex:(unsigned int)fp8;
- (unsigned int)index;
- (id)alarmView;
- (void)refreshUI:(id)fp8 animated:(BOOL)fp12;
- (void)_alarmActiveChanged:(id)fp8;
- (void)setAlarmActiveDelegate:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

