/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class AlarmScheduleLayoutAttributes, UILabel, UIView;

@interface AlarmScheduleCollectionCell : _ADClientAddValueForScalarKey
{
    AlarmScheduleLayoutAttributes *_attributes;
    UIView *_tileView;
    UILabel *_titleLabel;
}

+ (float)height;
- (void)applyLayoutAttributes:(id)fp8;
- (void)setSelected:(BOOL)fp8;
- (BOOL)bodyContainsPoint:(struct CGPoint)fp8;
- (void)updateColor;
- (void)updateTitleLabel;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)layoutSubviews;
- (id)alarmId;
- (id)description;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

