/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class NSString;

@interface AlarmScheduleLayoutAttributes : _ADClientAddValueForScalarKey
{
    NSString *_alarmId;
    int _day;
    BOOL _active;
    BOOL _showsTitle;
    NSString *_title;
}

- (void)setTitle:(id)fp8;
- (id)title;
- (void)setShowsTitle:(BOOL)fp8;
- (BOOL)showsTitle;
- (void)setActive:(BOOL)fp8;
- (BOOL)isActive;
- (void)setDay:(int)fp8;
- (int)day;
- (void)setAlarmId:(id)fp8;
- (id)alarmId;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEqual:(id)fp8;

@end

