/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "AlarmActiveDelegate-Protocol.h"
#import "AlarmDelegate-Protocol.h"
#import "EditAlarmViewControllerDelegate-Protocol.h"
#import "StateManagement-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class Alarm, AlarmCollectionEditController, CADisplayLink, EditAlarmViewController, UILongPressGestureRecognizer, UIPopoverController;

@interface AlarmPadViewController : _ADClientAddValueForScalarKey <UICollectionViewDataSource, UICollectionViewDelegate, UIPopoverControllerDelegate, UIGestureRecognizerDelegate, EditAlarmViewControllerDelegate, AlarmDelegate, AlarmActiveDelegate, StateManagement>
{
    UIPopoverController *_addOrEditPopover;
    EditAlarmViewController *_addController;
    AlarmCollectionEditController *_editListController;
    struct CGRect _previousAlarmsViewport;
    UILongPressGestureRecognizer *_alarmDragRecognizer;
    Alarm *_draggingAlarm;
    CADisplayLink *_dragScrollDisplayLink;
    BOOL _dragScrollingUp;
    double _dragScrollTimestamp;
}

- (id)defaultPNGName;
- (void)saveState;
- (void)reloadState;
- (void)activeChangedForAlarm:(id)fp8 active:(BOOL)fp12;
- (void)alarmDidUpdate:(id)fp8;
- (void)didDeleteAlarm:(id)fp8;
- (void)didEditAlarm:(id)fp8;
- (void)dismissAddViewController:(id)fp8;
- (void)cleanUpPopover;
- (void)commitAddOrEditOperation;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (BOOL)popoverControllerShouldDismissPopover:(id)fp8;
- (void)scrollAlarmSchedule:(id)fp8;
- (void)endAlarmDragAndSave:(BOOL)fp8;
- (void)updateAlarmDrag;
- (void)beginAlarmDrag;
- (void)handleAlarmDrag:(id)fp8;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (void)collectionView:(id)fp8 didDeselectItemAtIndexPath:(id)fp12;
- (BOOL)collectionView:(id)fp8 shouldDeselectItemAtIndexPath:(id)fp12;
- (void)collectionView:(id)fp8 didSelectItemAtIndexPath:(id)fp12;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (int)numberOfSectionsInCollectionView:(id)fp8;
- (void)viewDidLayoutSubviews;
- (void)viewDidUnload;
- (void)loadView;
- (void)viewWillTransitionToSize:(struct CGSize)fp8 withTransitionCoordinator:(id)fp16;
- (void)selectAlarm:(id)fp8 scroll:(BOOL)fp12;
- (id)selectedAlarm;
- (id)contentView;
- (void)didSuspend;
- (void)showEditView;
- (void)showAddView;
- (void)refreshButtonStates;
- (void)dealloc;
- (id)init;

@end

