/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class Alarm, AlarmTitleAndRepeatView, MTDateLabel, NSCalendar, NSDate, NSLayoutConstraint, NSMutableArray, UISwitch, UIView, _UIContentUnavailableView;

@interface AlarmDetailView : _ADClientAddValueForScalarKey
{
    Alarm *_alarm;
    NSCalendar *_calendar;
    NSDate *_baseDate;
    MTDateLabel *_timeLabel;
    AlarmTitleAndRepeatView *_titleAndRepeatView;
    UISwitch *_enabledSwitch;
    UIView *_keylineView;
    id <AlarmActiveDelegate> _delegate;
    _UIContentUnavailableView *_noAlarmsView;
    NSMutableArray *_spacerViews;
    NSDate *_time;
    NSLayoutConstraint *_timeLabelBaselineOffsetConstraint;
    NSLayoutConstraint *_timeLabelHorizontalCenteringConstraint;
    NSLayoutConstraint *_switchTopPaddingConstraint;
}

+ (id)colorForBackground;
- (void)setSwitchTopPaddingConstraint:(id)fp8;
- (id)switchTopPaddingConstraint;
- (void)setTimeLabelHorizontalCenteringConstraint:(id)fp8;
- (id)timeLabelHorizontalCenteringConstraint;
- (void)setTimeLabelBaselineOffsetConstraint:(id)fp8;
- (id)timeLabelBaselineOffsetConstraint;
- (id)time;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)alarm;
- (void)refreshUIAnimated:(BOOL)fp8;
- (void)refreshTimeView;
- (void)setTime:(id)fp8;
- (void)setAlarm:(id)fp8;
- (void)handleEnabledChanged:(id)fp8;
- (void)handleSignificantTimeChange:(id)fp8;
- (void)configureAutolayout;
- (void)updateLabelConstraints:(BOOL)fp8;
- (void)updateConstraints;
- (void)setShowingNoAlarms:(BOOL)fp8;
- (BOOL)isShowingNoAlarms;
- (void)dealloc;
- (float)defaultHeightForInterfaceOrientation:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

