/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class AlarmScheduleGridView;

@interface AlarmScheduleCollectionView : _ADClientAddValueForScalarKey
{
    AlarmScheduleGridView *_gridView;
}

- (id)gridView;
- (id)frontmostVisibleCellWithAlarmBodyContainingPoint:(struct CGPoint)fp8;
- (void)updateGridLayout;
- (id)collectionViewLayout;
- (void)setContentOffset:(struct CGPoint)fp8;
- (void)setContentSize:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)setShowingNoAlarms:(BOOL)fp8;
- (BOOL)isShowingNoAlarms;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 collectionViewLayout:(id)fp24;

@end

