/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class NSString;

@interface AlarmScheduleLayoutData : _ADClientAddValueForScalarKey
{
    NSString *_alarmId;
    int _hour;
    int _minute;
    unsigned int _daySetting;
    BOOL _active;
    BOOL _snoozed;
    NSString *_title;
    float _timePositionForItems;
    int _daysForItems[7];
    int _cellLayoutForItems[7];
}

+ (BOOL)doesTimePosition:(float)fp8 overlapWithTimePosition:(float)fp12 overlapPercent:(float)fp16;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setSnoozed:(BOOL)fp8;
- (BOOL)isSnoozed;
- (void)setActive:(BOOL)fp8;
- (BOOL)isActive;
- (unsigned int)daySetting;
- (int)minute;
- (int)hour;
- (void)setAlarmId:(id)fp8;
- (id)alarmId;
- (id)debugDescription;
- (id)description;
- (int)visualFirstItemWithLayout:(id)fp8;
- (id)layout:(id)fp8 itemsInDayRange:(CDAnonymousStruct2)fp12;
- (int)layout:(id)fp8 itemForDay:(int)fp12;
- (struct CGRect)layout:(id)fp8 frameForItem:(int)fp12;
- (BOOL)doesOverlapWithLayoutData:(id)fp8 fullOverlapOnly:(BOOL)fp12;
- (int)layout:(id)fp8 dayForItem:(int)fp12;
- (id)allDaysForLayout:(id)fp8;
- (void)setCellLayout:(int)fp8 forDay:(int)fp12;
- (int)cellLayoutForDay:(int)fp8;
- (void)setDaySetting:(unsigned int)fp8;
- (int)compareToHour:(int)fp8 minute:(int)fp12;
- (int)compareToTime:(id)fp8;
- (void)setHour:(int)fp8 minute:(int)fp12;
- (void)reset;
- (void)dealloc;
- (id)init;

@end

