/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class UILabel;

@interface AlarmTitleAndRepeatView : _ADClientAddValueForScalarKey
{
    float _previousWidth;
    UILabel *_titleLabel;
    UILabel *_repeatLabel;
}

- (id)repeatLabel;
- (id)titleLabel;
- (void)layoutSubviews;
- (void)_noteLayoutChange;
- (void)setRepeatText:(id)fp8;
- (void)setTitle:(id)fp8;
- (struct CGSize)intrinsicContentSize;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

