/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "UIApplicationDelegate-Protocol.h"

@class MobileTimerSecureWindow, MobileTimerTabBarController, NSString, NSTimer;

@interface AppController : _ADClientAddValueForScalarKey <UIApplicationDelegate>
{
    BOOL _initializationPerformed;
    NSTimer *_userPreferencesCommitTimer;
    MobileTimerSecureWindow *_window;
    MobileTimerTabBarController *_tabBarController;
    NSString *_currentTestName;
    int _iterations;
}

+ (id)tintColor;
- (void)application:(id)fp8 didSnoozeLocalNotification:(id)fp12;
- (void)application:(id)fp8 didReceiveLocalNotification:(id)fp12;
- (void)applicationWillTerminate:(id)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)handleLocalNotificationsChangedWithFullReload:(BOOL)fp8;
- (void)handleUserPreferencesChangedWithScheduledLocalNotificationsRefresh:(BOOL)fp8;
- (void)commitUserPreferences;
- (void)scheduleUserPreferencesCommit;
- (void)cancelScheduledUserPreferencesCommit;
- (void)saveState;
- (void)initWindowAndViewControllers;
- (BOOL)application:(id)fp8 openURL:(id)fp12 sourceApplication:(id)fp16 annotation:(id)fp20;
- (void)applicationDidFinishLaunching:(id)fp8;
- (void)dealloc;
- (id)containerViewController;
- (id)copyInvalidAlarmsLog;
- (id)invalidAlarmsDetected;
- (void)resetInvalidAlarmsLogging;
- (BOOL)runTest:(id)fp8 options:(id)fp12;
- (void)application:(id)fp8 didFailToContinueUserActivityWithType:(id)fp12 error:(id)fp16;
- (BOOL)application:(id)fp8 continueUserActivity:(id)fp12 restorationHandler:(id)fp(null);
- (BOOL)application:(id)fp8 willContinueUserActivityWithType:(id)fp12;
- (void)_didPageFullScreenWorldClock:(id)fp8;
- (void)_didPageWorldClock:(id)fp8;
- (void)_didExitFullScreenClock:(id)fp8;
- (void)_didEnterFullScreenClock:(id)fp8;
- (void)_windowDidRotate:(id)fp8;
- (void)_runRotationTest;
- (void)_selectViewController:(id)fp8;
- (void)_spinMainRunLoop;
- (void)_runScrollTest:(id)fp8;
- (void)finishedTest:(id)fp8 extraResults:(id)fp12;
- (void)startedTest:(id)fp8;

@end

