/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "UITextFieldDelegate-Protocol.h"

@class UITextField;

@interface BookmarkTextEntryTableViewCell : _ADClientAddValueForScalarKey <UITextFieldDelegate>
{
    UITextField *_textField;
}

- (void)dealloc;
- (id)textField;
- (void)setUserInteractionEnabled:(BOOL)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)layoutSubviews;
- (id)initWithText:(id)fp8 autoCapsType:(int)fp12;

@end

