/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@interface CenteredCellUITableView : _ADClientAddValueForScalarKey
{
    struct CGRect _keyboardFrame;
}

- (void)setKeyboardFrame:(struct CGRect)fp8;
- (struct CGRect)keyboardFrame;
- (void)layoutSubviews;

@end

