/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@interface ChunkedGridLayoutAttributes : _ADClientAddValueForScalarKey
{
    unsigned int _gridPosition;
}

- (void)setGridPosition:(unsigned int)fp8;
- (unsigned int)gridPosition;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEqual:(id)fp8;

@end

