/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class NSMutableArray, NSMutableDictionary;

@interface ChunkedGridLayout : _ADClientAddValueForScalarKey
{
    int _rowsPerChunk;
    int _columnsPerChunk;
    int _scrollDirection;
    int _fillFirstDirection;
    int _updatesMovementAllowed;
    int _boundsChangeMovementAllowed;
    id <ChunkedGridLayoutDelegate> _delegate;
    struct CGSize _itemSize;
    struct CGSize _currentBoundsSize;
    NSMutableArray *_sectionFrames;
    NSMutableArray *_allItemFrames;
    NSMutableDictionary *_cachedAttributes;
    NSMutableDictionary *_previousCachedAttributes;
    NSMutableDictionary *_finalAttributes;
    NSMutableDictionary *_initialAttributes;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setBoundsChangeMovementAllowed:(int)fp8;
- (int)boundsChangeMovementAllowed;
- (void)setUpdatesMovementAllowed:(int)fp8;
- (int)updatesMovementAllowed;
- (int)fillFirstDirection;
- (int)scrollDirection;
- (int)columnsPerChunk;
- (int)rowsPerChunk;
- (id)debugDescription;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)fp8;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)fp8;
- (void)finalizeAnimatedBoundsChange;
- (void)prepareForAnimatedBoundsChange:(struct CGRect)fp8;
- (void)finalizeCollectionViewUpdates;
- (void)prepareForCollectionViewUpdates:(id)fp8;
- (void)calculateAnimationLayoutAttributesWithMovementAllowed:(int)fp8 updates:(id)fp12;
- (struct CGSize)collectionViewContentSize;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(struct CGRect)fp8;
- (id)layoutAttributesForItemAtIndexPath:(id)fp8;
- (id)layoutAttributesForElementsInRect:(struct CGRect)fp8;
- (id)indexPathsForElementsInRect:(struct CGRect)fp8;
- (struct CGRect)frameForItemAtIndexPath:(id)fp8;
- (struct CGRect)frameForSection:(int)fp8;
- (void)calculateAllFrames;
- (void)prepareLayout;
- (void)resetAllFramesWithInvalidation:(BOOL)fp8;
- (int)chunkIndexForItemAtIndexPath:(id)fp8;
- (void)setFillFirstDirection:(int)fp8;
- (void)setScrollDirection:(int)fp8;
- (void)setColumnsPerChunk:(int)fp8;
- (void)setRowsPerChunk:(int)fp8;
- (int)cellsPerChunk;
- (void)dealloc;
- (id)init;

@end

