/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class NSString;

@interface ClockSearchCell : _ADClientAddValueForScalarKey
{
    NSString *_contentString;
}

- (void)setContentString:(id)fp8;
- (id)contentString;
- (id)_contentString;
- (void)dealloc;

@end

