/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class Alarm, EditAlarmView;

@interface EditAlarmViewController : _ADClientAddValueForScalarKey <UITableViewDataSource, UITableViewDelegate>
{
    id <EditAlarmViewControllerDelegate> _delegate;
    EditAlarmView *_editAlarmView;
    BOOL _edited;
    BOOL _editingFinished;
    BOOL _newAlarm;
    Alarm *_alarm;
    int _editingAlarmSetting;
}

+ (struct CGSize)desiredContentSize;
- (id)delegate;
- (id)alarm;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (unsigned int)supportedInterfaceOrientations;
- (void)handleSuspend;
- (void)handlePickerChanged;
- (void)setDelegate:(id)fp8;
- (void)startEditingSetting:(int)fp8;
- (void)_snoozeControlChanged:(id)fp8;
- (void)_doneButtonClicked:(id)fp8;
- (void)_cancelButtonClicked:(id)fp8;
- (void)saveAlarmOnlyIfEdited:(BOOL)fp8;
- (void)markAsEdited;
- (void)dealloc;
- (id)initWithAlarm:(id)fp8;

@end

