/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FullScreenWorldClockCollectionController.h"

@interface FullScreenSmallClockCollectionController : FullScreenWorldClockCollectionController
{
}

- (void)collectionView:(id)fp8 didSelectItemAtIndexPath:(id)fp12;
- (id)init;

@end

