/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "StopWatchLapCell-Protocol.h"

@class UILabel, UIView;

@interface LapPadTableViewCell : _ADClientAddValueForScalarKey <StopWatchLapCell>
{
    int _lap;
    double _time;
    double _runningTotal;
    UILabel *_lapLabel;
    UILabel *_runningTotalLabel;
    UILabel *_timeLabel;
    UIView *_keylineView;
    int _cellPosition;
}

+ (float)leftLabelCenterXToLeading;
+ (float)rightLabelCenterXToTrailing;
+ (float)rowHeight;
- (void)setRunningTotal:(double)fp8;
- (double)runningTotal;
- (int)cellPosition;
- (void)setTime:(double)fp8;
- (double)time;
- (void)setLap:(int)fp8;
- (int)lap;
- (id)_accessibilityFormatTime:(double)fp8 showHours:(char *)fp16 showSubseconds:(BOOL)fp20;
- (void)handleLocaleChange;
- (void)layoutSubviews;
- (void)resetLapFormatter;
- (void)setupLapFormatter;
- (void)prepareForReuse;
- (void)setCellPosition:(int)fp8;
- (void)dealloc;
- (void)setBackgroundColor:(id)fp8;
- (void)internalSetBackgroundColor:(id)fp8;
- (id)init;

@end

