/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class UILabel;

@interface LapPadTableViewHeaderView : _ADClientAddValueForScalarKey
{
    UILabel *_leftColumnHeader;
    UILabel *_centerColumnHeader;
    UILabel *_rightColumnHeader;
}

+ (float)defaultHeight;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

