/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class WorldClockMapView;

@interface MapCollectionCell : _ADClientAddValueForScalarKey
{
    WorldClockMapView *_mapView;
    struct UIEdgeInsets _padding;
}

- (struct UIEdgeInsets)padding;
- (id)mapView;
- (void)setPadding:(struct UIEdgeInsets)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

