/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class UINavigationController;

@interface MobileTimerTabBarController : _ADClientAddValueForScalarKey
{
    UINavigationController *_stopwatchNavController;
    UINavigationController *_timerNavController;
    UINavigationController *_alarmNavControllerSmall;
    UINavigationController *_alarmNavController;
    UINavigationController *_worldClockNavControllerSmall;
    UINavigationController *_worldClockNavController;
}

- (id)timerViewController;
- (id)stopwatchViewController;
- (id)alarmViewController;
- (id)worldClockViewController;
- (id)topViewControllerForTab:(int)fp8;
- (id)navigationControllerForHorizontalSizeClass:(int)fp8 verticalSizeClass:(int)fp12 atIndex:(unsigned int)fp16;
- (void)invalidateViewControllers;
- (void)traitCollectionDidChange:(id)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewWillAppear:(BOOL)fp8;
- (void)dealloc;

@end

