/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@interface MTCircleButton : _ADClientAddValueForScalarKey
{
    unsigned int _buttonCircleSize;
}

- (unsigned int)buttonCircleSize;
- (void)setColor:(unsigned int)fp8 forState:(unsigned int)fp12;
- (void)setButtonCircleSize:(unsigned int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

