/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class MTCircleButton;

@interface MTStopwatchController : _ADClientAddValueForScalarKey
{
    id <StopWatchControlsTarget> _target;
    MTCircleButton *_leftButton;
    MTCircleButton *_rightButton;
    int _mode;
    unsigned int _buttonSize;
}

- (unsigned int)buttonSize;
- (int)mode;
- (id)rightButton;
- (id)leftButton;
- (id)target;
- (void)setMode:(int)fp8 force:(BOOL)fp12;
- (void)setMode:(int)fp8;
- (void)_rightButtonDown:(id)fp8;
- (void)_leftButtonDown:(id)fp8;
- (void)setButtonSize:(unsigned int)fp8;
- (void)dealloc;
- (id)initWithTarget:(id)fp8;

@end

