/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class MTCircleButton;

@interface MTTimerButtonsController : _ADClientAddValueForScalarKey
{
    id <TimerControlsTarget> _target;
    MTCircleButton *_leftButton;
    MTCircleButton *_rightButton;
    int _state;
    unsigned int _buttonSize;
}

- (unsigned int)buttonSize;
- (int)state;
- (id)rightButton;
- (id)leftButton;
- (id)target;
- (void)setState:(int)fp8;
- (void)_rightButtonTapped:(id)fp8;
- (void)_leftButtonTapped:(id)fp8;
- (void)setButtonSize:(unsigned int)fp8;
- (void)dealloc;
- (id)initWithTarget:(id)fp8;

@end

