/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class TimerTimeView, UIDatePicker, UIView;

@interface MTTimerPickerCell : _ADClientAddValueForScalarKey
{
    UIView *_keylineView;
    UIView *_pickerBackgroundView;
    UIDatePicker *_picker;
    TimerTimeView *_timeView;
    int _state;
}

- (int)state;
- (id)timeView;
- (id)picker;
- (void)layoutSubviews;
- (void)setState:(int)fp8;
- (void)setState:(int)fp8 animated:(BOOL)fp12;
- (void)dealloc;
- (id)initWithPicker:(id)fp8 timeView:(id)fp12 reuseIdentifier:(id)fp16;

@end

