/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TimeView.h"

@class UILabel;

@interface StopwatchTimeView : TimeView
{
    double _currentLapTimeInterval;
    UILabel *_currentLapTimeLabel;
    int _style;
}

+ (float)defaultHeight;
- (void)setStyle:(int)fp8;
- (int)style;
- (double)currentLapTime;
- (void)setCurrentLapTime:(double)fp8;
- (BOOL)showSubseconds;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)_layoutWithSize:(struct CGSize)fp8 maxY:(float *)fp16;
- (void)handleLocaleChange;
- (void)_updateCurrentLapTime;
- (void)dealloc;
- (id)init;
- (void)configureBackground;
- (void)configureTimeLabel;

@end

