/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class UIBarButtonItem, UITableView, UIView, _UIContentUnavailableView;

@interface TableViewController : _ADClientAddValueForScalarKey <UITableViewDelegate, UITableViewDataSource>
{
    UIView *_backgroundView;
    UITableView *_tableView;
    UIBarButtonItem *_addButton;
    _UIContentUnavailableView *_noItemsView;
}

- (id)addButton;
- (id)tableView;
- (id)addViewController;
- (int)numberOfItems;
- (float)itemsTableRowHeight;
- (id)noItemsText;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (float)tableViewSpacingForExtraSeparators:(id)fp8;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)reloadState;
- (void)viewDidUnload;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)_numberOfItemsDidChangeAnimated:(BOOL)fp8;
- (void)_layoutNoItemsLabel;
- (void)dismissAddViewController:(id)fp8;
- (void)showAddView;
- (void)saveScrollPoint;
- (void)dealloc;
- (id)init;

@end

