/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "TimeView.h"

@interface TimerTimeView : TimeView
{
    int _style;
}

+ (float)defaultHeight;
- (int)style;
- (id)init;
- (void)configureBackground;
- (void)configureTimeLabel;
- (void)setStyle:(int)fp8;
- (void)sizeLabelToFit;
- (void)layoutSubviews;

@end

