/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class UILabel;

@interface TimeView : _ADClientAddValueForScalarKey
{
    double _timeValue;
    UILabel *_timeLabel;
    float _maxTimeLabelWidth;
}

+ (float)defaultHeight;
- (id)timeLabel;
- (double)time;
- (void)setTime:(double)fp8;
- (void)setTimeLabelFrame:(struct CGRect)fp8;
- (void)handleLocaleChange;
- (void)layoutSubviews;
- (void)dealloc;
- (id)init;
- (void)sizeLabelToFit;
- (void)configureBackground;
- (void)configureTimeLabel;
- (BOOL)showSubseconds;

@end

