/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TimerControlsTarget <NSObject>
- (void)showSoundPicker:(id)fp8;
- (void)pauseResumeTimer:(id)fp8;
- (void)cancelTimer:(id)fp8;
- (void)startTimer:(id)fp8;
@end

