/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CircleProgressView, MTTimerButtonsController, MTTimerPickerCell, NSString, TimerTimeView, UIButton, UIDatePicker, UITableView, UITableViewCell;

@interface TimerControlsView : _ADClientAddValueForScalarKey <UITableViewDataSource, UITableViewDelegate>
{
    TimerTimeView *_timeView;
    UIDatePicker *_timePicker;
    CircleProgressView *_circleBackground;
    CircleProgressView *_circleProgressView;
    UITableView *_tableView;
    MTTimerPickerCell *_pickerCell;
    UITableViewCell *_toneChooserCell;
    UIButton *_toneButton;
    NSString *_toneName;
    MTTimerButtonsController *_buttonsController;
    int _style;
    id <TimerControlsTarget> _delegate;
    int _state;
}

- (int)style;
- (int)state;
- (BOOL)tableView:(id)fp8 shouldHighlightRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)viewWillTransitionToSize:(struct CGSize)fp8 withTransitionCoordinator:(id)fp16;
- (void)layoutSubviews;
- (void)setButtonSize:(unsigned int)fp8;
- (void)_configureAndAddButton:(id)fp8;
- (void)setStyle:(int)fp8;
- (void)setState:(int)fp8;
- (void)setState:(int)fp8 animate:(BOOL)fp12;
- (void)setTimerToneName:(id)fp8;
- (void)handleLocaleChange;
- (void)setCountDownDuration:(double)fp8;
- (double)countDownDuration;
- (void)setTime:(double)fp8;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 style:(int)fp12;

@end

