/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class UITableView, WeatherAttributionView;

@interface WorldClockCollectionEditController : _ADClientAddValueForScalarKey <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_citiesView;
    WeatherAttributionView *_weatherAttributionView;
    id <WorldClockCollectionEditDelegate> _delegate;
}

- (id)delegate;
- (void)_selectedSegmentChanged:(id)fp8;
- (id)tableView:(id)fp8 viewForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (void)tableView:(id)fp8 moveRowAtIndexPath:(id)fp12 toIndexPath:(id)fp16;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)setDelegate:(id)fp8;
- (void)_updatePreferredContentSize;
- (void)loadSegmentedControl;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (void)dealloc;

@end

