/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class UIView, WorldClockView;

@interface WorldClockCollectionCell : _ADClientAddValueForScalarKey
{
    WorldClockView *_clockView;
    BOOL _verticalLines;
    BOOL _horizontalLines;
    UIView *_verticalLineView;
    UIView *_horizontalLineView;
}

+ (float)heightForOrientation:(int)fp8;
- (id)clockView;
- (void)applyLayoutAttributes:(id)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)layoutSubviews;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setClockView:(id)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

