/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "Clock-Protocol.h"

@class AnalogClockView, DigitalClockLabel, NSDateFormatter, NSTimeZone, UIButton, UIImageView, UILabel, WorldClockCity;

@interface WorldClockView : _ADClientAddValueForScalarKey <Clock>
{
    int _appearance;
    int _orientation;
    WorldClockCity *_city;
    NSTimeZone *_timeZone;
    id <WorldClockViewBackgroundHost> _backgroundHost;
    AnalogClockView *_analogClock;
    UIButton *_addClockButton;
    UIImageView *_highlightImageView;
    float _highlightAlpha;
    UILabel *_nameLabel;
    UILabel *_dayLabel;
    UILabel *_weatherLabel;
    UIButton *_listButton;
    NSDateFormatter *_timeFormatter;
    NSDateFormatter *_dayFormatter;
    int _nowInMinutes;
    DigitalClockLabel *_digitalClock;
}

+ (id)alphaMatchedImageWithColor:(id)fp8 forImage:(id)fp12;
- (id)listButton;
- (id)weatherLabel;
- (id)dayLabel;
- (id)nameLabel;
- (id)addClockButton;
- (id)digitalClock;
- (id)analogClock;
- (id)backgroundHost;
- (id)city;
- (int)appearance;
- (void)layoutSubviews;
- (void)handleLocaleChange;
- (void)handleNighttimeChange;
- (void)handleNoonCrossing;
- (void)handleMidnightCrossing;
- (void)updateFullscreenBackground;
- (void)updateColorThemeForFullscreen;
- (void)updateColorThemeForTile;
- (void)updateDay;
- (void)updateTime;
- (void)updateCombinedTime;
- (void)stop;
- (void)start;
- (void)weatherDataUpdated;
- (void)setCity:(id)fp8;
- (void)setupWorldClockAppearanceFullScreenDigital;
- (void)setupWorldClockAppearanceFullScreenSmall;
- (void)setupWorldClockAppearanceFullScreenLandscapeUpdatingOrientationOnly:(BOOL)fp8;
- (void)setupWorldClockAppearanceFullScreenPortraitUpdatingOrientationOnly:(BOOL)fp8;
- (void)setupWorldClockAppearanceTileAdd;
- (void)setupWorldClockAppearancePagingLandscape;
- (void)setupWorldClockAppearanceTile;
- (void)setupTimeDependentAppearanceProperties;
- (void)setupAnalogClockForStyle:(int)fp8;
- (double)coarseUpdateInterval;
- (double)updateInterval;
- (void)updateTimeContinuously:(int)fp8;
- (int)runMode;
- (void)setupAddButton;
- (void)removeAddButton;
- (void)removeAnalogClock;
- (void)updateAppearanceIfNeeded;
- (void)setAppearance:(int)fp8;
- (BOOL)doesAppearanceOrientationMatchInterfaceOrientation;
- (int)appearanceOrientationFromCurrentInterfaceOrientation;
- (void)setBackgroundHost:(id)fp8;
- (void)updateHighlightWithImage:(id)fp8;
- (void)setTileHighlighted:(BOOL)fp8;
- (BOOL)isTileHighlighted;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

