/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "AddClockViewControllerDelegate-Protocol.h"
#import "ChunkedGridLayoutDelegate-Protocol.h"
#import "StateManagement-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "WorldClockCollectionEditDelegate-Protocol.h"

@class FullScreenWorldClockCollectionController, NSIndexPath, NSTimer, UINavigationController, UIPinchGestureRecognizer, UIPopoverController, WorldClockPadContentView;

@interface WorldClockPadViewController : _ADClientAddValueForScalarKey <UICollectionViewDataSource, UICollectionViewDelegate, ChunkedGridLayoutDelegate, UIPopoverControllerDelegate, AddClockViewControllerDelegate, StateManagement, WorldClockCollectionEditDelegate, UIGestureRecognizerDelegate>
{
    UINavigationController *_addClockNavigationController;
    UIPopoverController *_editClocksController;
    FullScreenWorldClockCollectionController *_fullScreenClocksController;
    int _addedClockIndex;
    BOOL _networkReachable;
    NSTimer *_weatherUpdateTimer;
    UIPinchGestureRecognizer *_pinchGestureRecognizer;
    NSIndexPath *_pinchedIndexPath;
    BOOL _prefersStatusBarHidden;
    int _statusBarStyle;
    WorldClockPadContentView *_contentView;
}

- (void)setContentView:(id)fp8;
- (id)contentView;
- (id)defaultPNGName;
- (void)saveState;
- (void)reloadState;
- (void)collectionEditController:(id)fp8 moveCityAtIndex:(unsigned int)fp12 toIndex:(unsigned int)fp16;
- (void)collectionEditController:(id)fp8 removeCityAtIndex:(unsigned int)fp12;
- (void)weatherTemperatureUnitsDidChange;
- (void)dismissAddViewController:(id)fp8;
- (void)addClockViewController:(id)fp8 addCity:(id)fp12;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (BOOL)popoverControllerShouldDismissPopover:(id)fp8;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)updatePageIndicator;
- (void)dismissFullScreenClock;
- (void)presentFullScreenClockForIndexPath:(id)fp8 completion:(id)fp(null);
- (BOOL)prefersStatusBarHidden;
- (int)preferredStatusBarStyle;
- (void)setPrefersStatusBarHidden:(BOOL)fp8;
- (void)setStatusBarStyle:(int)fp8;
- (void)presentFullScreenClockForIndexPath:(id)fp8 afterDelay:(double)fp12;
- (BOOL)shouldPresentFullScreenClock;
- (void)collectionView:(id)fp8 didSelectItemAtIndexPath:(id)fp12;
- (void)addClock:(id)fp8;
- (BOOL)collectionView:(id)fp8 shouldSelectItemAtIndexPath:(id)fp12;
- (BOOL)collectionView:(id)fp8 shouldHighlightItemAtIndexPath:(id)fp12;
- (struct CGSize)sizeForItemWithLayout:(id)fp8;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (void)handleApplicationDidEnterBackground;
- (void)handleApplicationWillEnterForeground;
- (void)viewWillTransitionToSize:(struct CGSize)fp8 withTransitionCoordinator:(id)fp16;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)stopUpdates;
- (void)startUpdates;
- (void)reachabilityChanged:(id)fp8;
- (void)viewDidLayoutSubviews;
- (void)viewDidUnload;
- (void)loadView;
- (void)setLeftBarButton:(BOOL)fp8 animated:(BOOL)fp12;
- (unsigned int)supportedInterfaceOrientations;
- (void)pinchAction:(id)fp8;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (id)fullScreenClocksController;
- (void)updateMapWeatherDataForAllCities;
- (void)updateMapWeatherDataForCities:(id)fp8;
- (void)updateClocksForSize:(struct CGSize)fp8;
- (void)scrollToPageContainingIndexPath:(id)fp8;
- (void)toggleEditView;
- (BOOL)shouldToggleEditView;
- (void)showAddView;
- (BOOL)shouldShowAddView;
- (void)didSuspend;
- (void)dealloc;
- (id)init;

@end

