/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class UIImage;

@interface WorldClockPageControl : _ADClientAddValueForScalarKey
{
    UIImage *_indicator;
    UIImage *_currentIndicator;
}

- (id)_pageIndicatorCurrentImageForPage:(int)fp8;
- (id)_pageIndicatorImageForPage:(int)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8 useNeutralColor:(BOOL)fp24;

@end

