/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PagingLandscapeCollectionViewController.h"

#import "AddClockViewControllerDelegate-Protocol.h"
#import "StateManagement-Protocol.h"

@class FullScreenSmallClockCollectionController, MapCollectionCell, NSTimer, WorldClockCollectionEditController;

@interface WorldClockViewController : PagingLandscapeCollectionViewController <StateManagement, AddClockViewControllerDelegate>
{
    int _clockStyle;
    FullScreenSmallClockCollectionController *_fullScreenClocksController;
    MapCollectionCell *_mapCollectionCell;
    struct UIEdgeInsets _mapCollectionCellPadding;
    NSTimer *_weatherUpdateTimer;
    BOOL _networkReachable;
    WorldClockCollectionEditController *_collectionEditController;
}

- (id)defaultPNGName;
- (void)dismissFullScreenClock;
- (void)presentFullScreenClockForIndexPath:(id)fp8 completion:(id)fp(null);
- (void)presentFullScreenClockForIndexPath:(id)fp8 afterDelay:(double)fp12;
- (BOOL)shouldPresentFullScreenClock;
- (void)collectionView:(id)fp8 didSelectItemAtIndexPath:(id)fp12;
- (struct CGSize)collectionView:(id)fp8 layout:(id)fp12 sizeForItemAtIndexPath:(id)fp16;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (int)numberOfSectionsInCollectionView:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 moveRowAtIndexPath:(id)fp12 toIndexPath:(id)fp16;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (void)addClockViewController:(id)fp8 addCity:(id)fp12;
- (id)addViewController;
- (void)showAddView;
- (void)saveScrollPoint;
- (int)numberOfItems;
- (float)itemsTableRowHeight;
- (id)noItemsText;
- (void)toggleClockMode;
- (void)saveState;
- (void)reloadState;
- (void)willTransitionToTraitCollection:(id)fp8 withTransitionCoordinator:(id)fp12;
- (id)pagingCollectionViewRotationBackgroundColor;
- (void)pagingCollectionViewDidDisappear;
- (void)pagingCollectionViewDidAppear;
- (void)updateMapWeatherDataForAllCities;
- (void)updateMapWeatherDataForCities:(id)fp8;
- (void)stopWeatherUpdates;
- (void)startWeatherUpdates;
- (void)reachabilityChanged:(id)fp8;
- (void)collectionEditController:(id)fp8 moveCityAtIndex:(unsigned int)fp12 toIndex:(unsigned int)fp16;
- (void)collectionEditController:(id)fp8 removeCityAtIndex:(unsigned int)fp12;
- (void)weatherTemperatureUnitsDidChange;
- (void)_dismissEditController:(id)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)pagingCollectionViewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

