/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@interface WorldClockCollectionView : _ADClientAddValueForScalarKey
{
}

- (void)setContentOffset:(struct CGPoint)fp8 animated:(BOOL)fp16;
- (void)setContentOffset:(struct CGPoint)fp8;
- (id)initWithFrame:(struct CGRect)fp8 collectionViewLayout:(id)fp24;

@end

