/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class WorldClockCollectionView, WorldClockMapView, WorldClockPageControl;

@interface WorldClockPadContentView : _ADClientAddValueForScalarKey
{
    WorldClockCollectionView *_clocksView;
    WorldClockPageControl *_clocksPageIndicator;
    WorldClockMapView *_mapView;
}

- (id)mapView;
- (id)clocksPageIndicator;
- (id)clocksView;
- (void)scrollToCurrentPage;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

