/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WorldClockCollectionEditDelegate <NSObject>
- (void)collectionEditController:(id)fp8 moveCityAtIndex:(unsigned int)fp12 toIndex:(unsigned int)fp16;
- (void)collectionEditController:(id)fp8 removeCityAtIndex:(unsigned int)fp12;
- (void)weatherTemperatureUnitsDidChange;
@end

