/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

@class NSDate, NSDateFormatter, NSMutableDictionary, NSTimer, UIButton, UIImage, UIImageView, WorldClockMapCityView;

@interface WorldClockMapView : _ADClientAddValueForScalarKey
{
    NSMutableDictionary *_cityViews;
    WorldClockMapCityView *_addedCityView;
    NSDateFormatter *_timeFormatter;
    float _maxTimeStringWidth;
    float _maxTemperatureStringWidth;
    UIImageView *_mapWithTerminator;
    UIImage *_terminatorImages[2];
    NSDate *_terminatorTimestamp;
    NSTimer *_terminatorTimer;
    UIButton *_twcButton;
}

+ (void)updateNewYearsDay;
- (id)terminatorPathForDayOfYear:(double)fp8 orientation:(int)fp16;
- (void)twcButtonPressed;
- (void)updateTerminator;
- (void)scheduleTerminatorUpdate;
- (void)cancelTerminatorUpdate;
- (double)terminatorUpdateInterval;
- (void)stopUpdatingTime;
- (void)startUpdatingTime;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)viewWillTransitionToSize:(struct CGSize)fp8 withTransitionCoordinator:(id)fp16;
- (void)weatherDataUpdatedForCities:(id)fp8;
- (void)removeCity:(id)fp8;
- (void)addCity:(id)fp8;
- (void)addCity:(id)fp8 animated:(BOOL)fp12;
- (float)maxWidthForTemperatureStringWithFont:(id)fp8;
- (float)maxWidthForDateStringWithFont:(id)fp8;
- (void)handleSignificantTimeChange:(id)fp8;
- (void)handleLocaleChange;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

