/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADClientAddValueForScalarKey.h"

#import "Clock-Protocol.h"

@class NSDateFormatter, UIImageView, UILabel, WorldClockCity;

@interface WorldClockMapCityView : _ADClientAddValueForScalarKey <Clock>
{
    WorldClockCity *_city;
    UILabel *_timeLabel;
    UILabel *_nameLabel;
    UILabel *_temperatureLabel;
    UIImageView *_conditionImageView;
    NSDateFormatter *_timeFormatter;
    int _weatherIconPlacement;
    BOOL _doneFirstLayout;
}

+ (id)secondaryLabelFont;
- (int)weatherIconPlacement;
- (id)timeFormatter;
- (id)city;
- (void)stop;
- (void)start;
- (void)updateTime;
- (int)runMode;
- (void)setWeatherIconPlacement:(int)fp8;
- (void)layoutSubviews;
- (void)layoutIfNeeded;
- (struct CGPoint)hotspotOffset;
- (struct CGPoint)hotspotOffsetForPlacement:(int)fp8;
- (struct CGSize)sizeForIntersectionWithCityView:(id)fp8 atOrigin:(struct CGPoint)fp12 selfOrigin:(struct CGPoint)fp20;
- (id)labelViews;
- (struct CGRect)conditionImageFrameForPlacement:(int)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setCity:(id)fp8;
- (void)weatherDataUpdated;
- (id)temperatureString;
- (void)setConditionCodeFromCity:(id)fp8;
- (void)setTemperatureLabelWidth:(float)fp8;
- (void)setTimeLabelWidth:(float)fp8;
- (void)handleLocaleChange;
- (void)setTimeFormatter:(id)fp8;
- (void)dealloc;
- (id)initWithCity:(id)fp8;

@end

